# Generated by Django 5.2.7 on 2026-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
