# Generated by Django 5.2.7 on 2026-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business_template_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='custom_schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
