# Generated by Django 5.2.7 on 2026-07-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_business_template_id_category_custom_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='business_template_id',
        ),
    ]
