# Generated by Django 6.0.2 on 2026-02-16 07:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('selected_category_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('type', models.CharField(choices=[('cover', 'Cover'), ('interior', 'Interior'), ('index', 'Index'), ('closing', 'Closing')], default='interior', max_length=20)),
                ('layout_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=50)),
                ('heading_color', models.CharField(max_length=50)),
                ('body_color', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=50)),
                ('font_collection', models.JSONField(default=dict)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='themes/')),
            ],
        ),
    ]
