# Generated by Django 5.2.7 on 2026-09-03 11:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_catalog_id_alter_catalogpage_id_alter_theme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('type', models.CharField(choices=[('full_catalog', 'Full Catalog Blueprint'), ('cover', 'Cover Page Template'), ('product_grid', 'Product Grid Layout')], default='full_catalog', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.TextField(blank=True, default='')),
                ('theme_id', models.CharField(blank=True, default='modern-slate', max_length=100)),
                ('pages_data', models.JSONField(blank=True, default=list)),
                ('grid_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
