# Generated by Django 5.2.7 on 2026-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_systemtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtemplate',
            name='type',
            field=models.CharField(choices=[('full_catalog', 'Full Catalog Blueprint'), ('cover', 'Cover Page Template'), ('product_grid', 'Product Grid Layout'), ('header', 'Master Header Template'), ('footer', 'Master Footer Template')], default='full_catalog', max_length=50),
        ),
    ]
