# Generated by Django 6.0.2 on 2026-02-18 05:37

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.ImageField(upload_to=media.models.media_upload_path),
        ),
    ]
