# Generated by Django 5.2.7 on 2026-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediaitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
