# Generated by Django 6.0.2 on 2026-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediaitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
