# Generated by Django 5.2.7 on 2026-07-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_custom_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_schema',
        ),
    ]
