# Generated by Django 5.2.7 on 2026-07-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_business_id_remove_user_custom_schema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessTemplate',
        ),
    ]
