# Generated by Django 5.2.7 on 2026-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_businesstemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='catalogmakerr.', max_length=100)),
                ('support_email', models.EmailField(default='support@catalogstudio.com', max_length=254)),
                ('allow_public_signup', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='System is currently under maintenance. We will be back shortly.')),
                ('enable_free_watermark', models.BooleanField(default=True)),
                ('watermark_text', models.CharField(default='Made with catalogmakerr.', max_length=200)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
